### ISSUE TITLE
python code appdaemon integration 

### ISSUE THREAD

**Issue by karataserol** [bruxy70/Heating#1]
First of all, thank you very much for this amazing share. I have a request from you. Although I have watched your videos 2-3 times, you do not explain how you run the python code you wrote in appdaeomon. can you help me how can i integrate any python code which is  i wrote into my dashboard automation .

thank you in advance

**Comment by bruxy70** [comment]
You have to install AppDaemon, and then you can install the AppDaemon automation. It will run automatically.
I made a video about AppDaemon some time ago https://youtu.be/vNib86rkEA0
It is probably more then you need, it also breaks down the code. But it does cover the installation and configuration.

**Comment by karataserol** [comment]
Thank You Mr.Vaclav  actually i subscribe to your channel and i watched almost all of your videos but As you mentioned, for in my system, the information does not automatically appear on my screen. Maybe I'm making a mistake because I didn't create any interfaces and unfortunately  The log status is added as follows without any problems, but I don't know how to integrate these data from now on. 


<2021-11-04 06:53:49.950826 INFO HASS: All startup conditions met
2021-11-04 06:53:49.948063 INFO HASS: Startup condition met: hass state=RUNNING
2021-11-04 06:53:49.922633 INFO AppDaemon: Running on port 5050
2021-11-04 06:53:49.910681 INFO AppDaemon: Starting Apps with 3 workers and 3 pins
2021-11-04 06:53:49.906401 INFO AppDaemon: Found 3 total apps
2021-11-04 06:53:49.897397 INFO AppDaemon: App 'first' added
2021-11-04 06:53:49.883013 INFO HASS: Evaluating startup conditions
2021-11-04 06:53:49.848397 INFO AppDaemon: App 'heating-control' added>

**Comment by bruxy70** [comment]
AppAaemon is a backend automation thing. It will basically change the state of entities, that's it. Then I just work with the Home Assistant dashboard interface as usual.
I think there is some dashboard feature, configured by `hadashboard:` , but I've never used it, I do not know how it works.

**Comment by karataserol** [comment]
Thank you for your information
